services:
  debian-latex:
    # Use the build: object, if you want to build the image from scratch. In this case, place the Dockerfile from the project root in the .devcontainer directory and comment out the image: object.
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: noctuidus/devcontainer-latex:{{TAG}}
    volumes:
      - type: bind
        source: "${PWD}"
        target: /ws
        consistency: cached
    environment:
      - TZ=${TZ:-Europe/Berlin}
      - TERM=xterm
    entrypoint: ["/bin/bash", "-c", "while sleep 1000; do :; done"]

