name: Create Release Zips

on:
  release:
    types: [published]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Debug: List directory contents
      - name: List repository contents
        run: |
          ls -R
        shell: bash

      # Create minimal release zip
      - name: Create minimal release zip
        run: |
          mkdir -p latex-devcontainer-minimal
          cp -r example/.devcontainer latex-devcontainer-minimal/
          # Update devcontainer.json to use prebuilt image
          sed -i 's|"build": {[^}]*}|"image": "noctuidus/devcontainer-latex:latest"|' latex-devcontainer-minimal/.devcontainer/devcontainer.json
          # Debug: Verify devcontainer.json
          cat latex-devcontainer-minimal/.devcontainer/devcontainer.json
          zip -r latex-devcontainer-minimal.zip latex-devcontainer-minimal
        shell: bash

      # Create full release zip
      - name: Create full release zip
        run: |
          mkdir -p latex-devcontainer-release/.devcontainer
          cp -r example/.devcontainer/* latex-devcontainer-release/.devcontainer/
          cp Dockerfile latex-devcontainer-release/.devcontainer/
          cp -r config latex-devcontainer-release/.devcontainer/
          # Update devcontainer.json to use local Dockerfile
          sed -i 's|"build": {[^}]*}|"build": {"dockerfile": "Dockerfile", "context": "."}|' latex-devcontainer-release/.devcontainer/devcontainer.json
          # Comment out image field in docker-compose.yml
          sed -i 's|^\(\s*image:.*\)$|#\1|' latex-devcontainer-release/.devcontainer/docker-compose.yml
          # Debug: Verify modified files
          cat latex-devcontainer-release/.devcontainer/devcontainer.json
          cat latex-devcontainer-release/.devcontainer/docker-compose.yml
          zip -r latex-devcontainer-release.zip latex-devcontainer-release
        shell: bash

      # Upload minimal release zip
      - name: Upload minimal release zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: latex-devcontainer-minimal.zip
          asset_name: latex-devcontainer-minimal.zip
          asset_content_type: application/zip

      # Upload full release zip
      - name: Upload full release zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: latex-devcontainer-release.zip
          asset_name: latex-devcontainer-release.zip
          asset_content_type: application/zip